{% set name = "curlify2" %}
{% set version = "1.0.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/curlify2-{{ version }}.tar.gz
  sha256: 2a9dc7b8902e1301f3600ccfa61905e9812583dba83798310db678fb9ed6e256

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - poetry
    - python >=3.6,<4.0
  run:
    - python >=3.6,<4.0
    - requests >=2.24.0,<3.0.0
    - responses >=0.12.0,<0.13.0

test:
  imports:
    - curlify2
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/marcuxyz/curlify2
  summary: Library to convert python requests and httpx object to curl command.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
